# Generated by Django 4.2.6 on 2024-01-29 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jonasapp', '0002_post_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
    ]
